import { MediaStatus } from "@/types/anilist-types";

export const statusEnums = [
  { normal: "Cancelled", query: "CANCELLED" },
  { normal: "Finished", query: "FINISHED" },
  { normal: "Upcoming", query: "NOT_YET_RELEASED" },
  { normal: "Ongoing", query: "RELEASING" },
] as const;
export const sortEnums = [
  { normal: "Popularity", query: "POPULAR_DESC" },
  { normal: "Trending", query: "TRENDING_DESC" },
  { normal: "Score", query: "SCORE_DESC" },
  { normal: "Latest", query: "START_DATE_DESC" },
] as const;
export const formatEnums = [
  { normal: "TV", query: "TV" },
  { normal: "Movie", query: "MOVIE" },
  { normal: "TV Short", query: "TV_SHORT" },
  { normal: "OVA", query: "OVA" },
  { normal: "ONA", query: "ONA" },
] as const;
export const seasonEnums = [
  { normal: "Spring", query: "SPRING" },
  { normal: "Summer", query: "SUMMER" },
  { normal: "Fall", query: "FALL" },
  { normal: "Winter", query: "WINTER" },
] as const;
export const genreEnums = [
  "Action",
  "Adventure",
  "Comedy",
  "Drama",
  "Ecchi",
  "Fantasy",
  "Hentai",
  "Horror",
  "Mahou Shoujo",
  "Mecha",
  "Music",
  "Mystery",
  "Psychological",
  "Romance",
  "Sci-Fi",
  "Slice of Life",
  "Sports",
  "Supernatural",
  "Thriller",
] as const;
export const tagEnums = [
  { name: "4-koma", isAdult: false },
  { name: "Achromatic", isAdult: false },
  { name: "Achronological Order", isAdult: false },
  { name: "Acrobatics", isAdult: false },
  { name: "Acting", isAdult: false },
  { name: "Adoption", isAdult: false },
  { name: "Advertisement", isAdult: false },
  { name: "Afterlife", isAdult: false },
  { name: "Age Gap", isAdult: false },
  { name: "Age Regression", isAdult: false },
  { name: "Agender", isAdult: false },
  { name: "Agriculture", isAdult: false },
  { name: "Ahegao", isAdult: true },
  { name: "Airsoft", isAdult: false },
  { name: "Alchemy", isAdult: false },
  { name: "Aliens", isAdult: false },
  { name: "Alternate Universe", isAdult: false },
  { name: "American Football", isAdult: false },
  { name: "Amnesia", isAdult: false },
  { name: "Amputation", isAdult: true },
  { name: "Anachronism", isAdult: false },
  { name: "Anal Sex", isAdult: true },
  { name: "Ancient China", isAdult: false },
  { name: "Angels", isAdult: false },
  { name: "Animals", isAdult: false },
  { name: "Anthology", isAdult: false },
  { name: "Anthropomorphism", isAdult: false },
  { name: "Anti-Hero", isAdult: false },
  { name: "Archery", isAdult: false },
  { name: "Armpits", isAdult: true },
  { name: "Aromantic", isAdult: false },
  { name: "Arranged Marriage", isAdult: false },
  { name: "Artificial Intelligence", isAdult: false },
  { name: "Asexual", isAdult: false },
  { name: "Ashikoki", isAdult: true },
  { name: "Asphyxiation", isAdult: true },
  { name: "Assassins", isAdult: false },
  { name: "Astronomy", isAdult: false },
  { name: "Athletics", isAdult: false },
  { name: "Augmented Reality", isAdult: false },
  { name: "Autobiographical", isAdult: false },
  { name: "Aviation", isAdult: false },
  { name: "Badminton", isAdult: false },
  { name: "Ballet", isAdult: false },
  { name: "Band", isAdult: false },
  { name: "Bar", isAdult: false },
  { name: "Baseball", isAdult: false },
  { name: "Basketball", isAdult: false },
  { name: "Battle Royale", isAdult: false },
  { name: "Biographical", isAdult: false },
  { name: "Bisexual", isAdult: false },
  { name: "Blackmail", isAdult: false },
  { name: "Board Game", isAdult: false },
  { name: "Boarding School", isAdult: false },
  { name: "Body Horror", isAdult: false },
  { name: "Body Image", isAdult: false },
  { name: "Body Swapping", isAdult: false },
  { name: "Bondage", isAdult: true },
  { name: "Boobjob", isAdult: true },
  { name: "Bowling", isAdult: false },
  { name: "Boxing", isAdult: false },
  { name: "Boys' Love", isAdult: false },
  { name: "Brainwashing", isAdult: false },
  { name: "Bullying", isAdult: false },
  { name: "Butler", isAdult: false },
  { name: "Calligraphy", isAdult: false },
  { name: "Camping", isAdult: false },
  { name: "Cannibalism", isAdult: false },
  { name: "Card Battle", isAdult: false },
  { name: "Cars", isAdult: false },
  { name: "Centaur", isAdult: false },
  { name: "Cervix Penetration", isAdult: true },
  { name: "CGI", isAdult: false },
  { name: "Cheating", isAdult: true },
  { name: "Cheerleading", isAdult: false },
  { name: "Chibi", isAdult: false },
  { name: "Chimera", isAdult: false },
  { name: "Chuunibyou", isAdult: false },
  { name: "Circus", isAdult: false },
  { name: "Class Struggle", isAdult: false },
  { name: "Classic Literature", isAdult: false },
  { name: "Classical Music", isAdult: false },
  { name: "Clone", isAdult: false },
  { name: "Coastal", isAdult: false },
  { name: "Cohabitation", isAdult: false },
  { name: "College", isAdult: false },
  { name: "Coming of Age", isAdult: false },
  { name: "Conspiracy", isAdult: false },
  { name: "Cosmic Horror", isAdult: false },
  { name: "Cosplay", isAdult: false },
  { name: "Cowboys", isAdult: false },
  { name: "Creature Taming", isAdult: false },
  { name: "Crime", isAdult: false },
  { name: "Criminal Organization", isAdult: false },
  { name: "Crossdressing", isAdult: false },
  { name: "Crossover", isAdult: false },
  { name: "Cult", isAdult: false },
  { name: "Cultivation", isAdult: false },
  { name: "Cumflation", isAdult: true },
  { name: "Cunnilingus", isAdult: true },
  { name: "Curses", isAdult: false },
  { name: "Cute Boys Doing Cute Things", isAdult: false },
  { name: "Cute Girls Doing Cute Things", isAdult: false },
  { name: "Cyberpunk", isAdult: false },
  { name: "Cyborg", isAdult: false },
  { name: "Cycling", isAdult: false },
  { name: "Dancing", isAdult: false },
  { name: "Death Game", isAdult: false },
  { name: "Deepthroat", isAdult: true },
  { name: "Defloration", isAdult: true },
  { name: "Delinquents", isAdult: false },
  { name: "Demons", isAdult: false },
  { name: "Denpa", isAdult: false },
  { name: "Desert", isAdult: false },
  { name: "Detective", isAdult: false },
  { name: "DILF", isAdult: true },
  { name: "Dinosaurs", isAdult: false },
  { name: "Disability", isAdult: false },
  { name: "Dissociative Identities", isAdult: false },
  { name: "Double Penetration", isAdult: true },
  { name: "Dragons", isAdult: false },
  { name: "Drawing", isAdult: false },
  { name: "Drugs", isAdult: false },
  { name: "Dullahan", isAdult: false },
  { name: "Dungeon", isAdult: false },
  { name: "Dystopian", isAdult: false },
  { name: "E-Sports", isAdult: false },
  { name: "Eco-Horror", isAdult: false },
  { name: "Economics", isAdult: false },
  { name: "Educational", isAdult: false },
  { name: "Elderly Protagonist", isAdult: false },
  { name: "Elf", isAdult: false },
  { name: "Ensemble Cast", isAdult: false },
  { name: "Environmental", isAdult: false },
  { name: "Episodic", isAdult: false },
  { name: "Ero Guro", isAdult: false },
  { name: "Erotic Piercings", isAdult: true },
  { name: "Espionage", isAdult: false },
  { name: "Estranged Family", isAdult: false },
  { name: "Exhibitionism", isAdult: true },
  { name: "Exorcism", isAdult: false },
  { name: "Facial", isAdult: true },
  { name: "Fairy", isAdult: false },
  { name: "Fairy Tale", isAdult: false },
  { name: "Fake Relationship", isAdult: false },
  { name: "Family Life", isAdult: false },
  { name: "Fashion", isAdult: false },
  { name: "Feet", isAdult: true },
  { name: "Fellatio", isAdult: true },
  { name: "Female Harem", isAdult: false },
  { name: "Female Protagonist", isAdult: false },
  { name: "Femboy", isAdult: false },
  { name: "Femdom", isAdult: true },
  { name: "Fencing", isAdult: false },
  { name: "Filmmaking", isAdult: false },
  { name: "Fingering", isAdult: true },
  { name: "Firefighters", isAdult: false },
  { name: "Fishing", isAdult: false },
  { name: "Fisting", isAdult: true },
  { name: "Fitness", isAdult: false },
  { name: "Flash", isAdult: false },
  { name: "Flat Chest", isAdult: true },
  { name: "Food", isAdult: false },
  { name: "Football", isAdult: false },
  { name: "Foreign", isAdult: false },
  { name: "Found Family", isAdult: false },
  { name: "Fugitive", isAdult: false },
  { name: "Full CGI", isAdult: false },
  { name: "Full Color", isAdult: false },
  { name: "Futanari", isAdult: true },
  { name: "Gambling", isAdult: false },
  { name: "Gangs", isAdult: false },
  { name: "Gekiga", isAdult: false },
  { name: "Gender Bending", isAdult: false },
  { name: "Ghost", isAdult: false },
  { name: "Go", isAdult: false },
  { name: "Goblin", isAdult: false },
  { name: "Gods", isAdult: false },
  { name: "Golf", isAdult: false },
  { name: "Gore", isAdult: false },
  { name: "Graduation Project", isAdult: false },
  { name: "Group Sex", isAdult: true },
  { name: "Guns", isAdult: false },
  { name: "Gyaru", isAdult: false },
  { name: "Hair Pulling", isAdult: true },
  { name: "Handball", isAdult: false },
  { name: "Handjob", isAdult: true },
  { name: "Henshin", isAdult: false },
  { name: "Heterosexual", isAdult: false },
  { name: "Hikikomori", isAdult: false },
  { name: "Hip-hop Music", isAdult: false },
  { name: "Historical", isAdult: false },
  { name: "Homeless", isAdult: false },
  { name: "Horticulture", isAdult: false },
  { name: "Human Experimentation", isAdult: false },
  { name: "Human Pet", isAdult: true },
  { name: "Hypersexuality", isAdult: true },
  { name: "Ice Skating", isAdult: false },
  { name: "Idol", isAdult: false },
  { name: "Incest", isAdult: true },
  { name: "Indigenous Cultures", isAdult: false },
  { name: "Inn", isAdult: false },
  { name: "Inseki", isAdult: true },
  { name: "Interspecies", isAdult: false },
  { name: "Irrumatio", isAdult: true },
  { name: "Isekai", isAdult: false },
  { name: "Iyashikei", isAdult: false },
  { name: "Jazz Music", isAdult: false },
  { name: "Josei", isAdult: false },
  { name: "Judo", isAdult: false },
  { name: "Kabuki", isAdult: false },
  { name: "Kaiju", isAdult: false },
  { name: "Karuta", isAdult: false },
  { name: "Kemonomimi", isAdult: false },
  { name: "Kids", isAdult: false },
  { name: "Kingdom Management", isAdult: false },
  { name: "Konbini", isAdult: false },
  { name: "Kuudere", isAdult: false },
  { name: "Lacrosse", isAdult: false },
  { name: "Lactation", isAdult: true },
  { name: "Language Barrier", isAdult: false },
  { name: "Large Breasts", isAdult: true },
  { name: "LGBTQ+ Themes", isAdult: false },
  { name: "Long Strip", isAdult: false },
  { name: "Lost Civilization", isAdult: false },
  { name: "Love Triangle", isAdult: false },
  { name: "Mafia", isAdult: false },
  { name: "Magic", isAdult: false },
  { name: "Mahjong", isAdult: false },
  { name: "Maids", isAdult: false },
  { name: "Makeup", isAdult: false },
  { name: "Male Harem", isAdult: false },
  { name: "Male Pregnancy", isAdult: true },
  { name: "Male Protagonist", isAdult: false },
  { name: "Manzai", isAdult: false },
  { name: "Marriage", isAdult: false },
  { name: "Martial Arts", isAdult: false },
  { name: "Masochism", isAdult: true },
  { name: "Masturbation", isAdult: true },
  { name: "Matchmaking", isAdult: false },
  { name: "Mating Press", isAdult: true },
  { name: "Matriarchy", isAdult: false },
  { name: "Medicine", isAdult: false },
  { name: "Medieval", isAdult: false },
  { name: "Memory Manipulation", isAdult: false },
  { name: "Mermaid", isAdult: false },
  { name: "Meta", isAdult: false },
  { name: "Metal Music", isAdult: false },
  { name: "MILF", isAdult: true },
  { name: "Military", isAdult: false },
  { name: "Mixed Gender Harem", isAdult: false },
  { name: "Mixed Media", isAdult: false },
  { name: "Modeling", isAdult: false },
  { name: "Monster Boy", isAdult: false },
  { name: "Monster Girl", isAdult: false },
  { name: "Mopeds", isAdult: false },
  { name: "Motorcycles", isAdult: false },
  { name: "Mountaineering", isAdult: false },
  { name: "Musical Theater", isAdult: false },
  { name: "Mythology", isAdult: false },
  { name: "Nakadashi", isAdult: true },
  { name: "Natural Disaster", isAdult: false },
  { name: "Necromancy", isAdult: false },
  { name: "Nekomimi", isAdult: false },
  { name: "Netorare", isAdult: true },
  { name: "Netorase", isAdult: true },
  { name: "Netori", isAdult: true },
  { name: "Ninja", isAdult: false },
  { name: "No Dialogue", isAdult: false },
  { name: "Noir", isAdult: false },
  { name: "Non-fiction", isAdult: false },
  { name: "Nudity", isAdult: false },
  { name: "Nun", isAdult: false },
  { name: "Office", isAdult: false },
  { name: "Office Lady", isAdult: false },
  { name: "Oiran", isAdult: false },
  { name: "Ojou-sama", isAdult: false },
  { name: "Omegaverse", isAdult: true },
  { name: "Orphan", isAdult: false },
  { name: "Otaku Culture", isAdult: false },
  { name: "Outdoor Activities", isAdult: false },
  { name: "Oyakodon", isAdult: true },
  { name: "Pandemic", isAdult: false },
  { name: "Parenthood", isAdult: false },
  { name: "Parkour", isAdult: false },
  { name: "Parody", isAdult: false },
  { name: "Pet Play", isAdult: true },
  { name: "Philosophy", isAdult: false },
  { name: "Photography", isAdult: false },
  { name: "Pirates", isAdult: false },
  { name: "Poker", isAdult: false },
  { name: "Police", isAdult: false },
  { name: "Politics", isAdult: false },
  { name: "Polyamorous", isAdult: false },
  { name: "Post-Apocalyptic", isAdult: false },
  { name: "POV", isAdult: false },
  { name: "Pregnancy", isAdult: false },
  { name: "Primarily Adult Cast", isAdult: false },
  { name: "Primarily Animal Cast", isAdult: false },
  { name: "Primarily Child Cast", isAdult: false },
  { name: "Primarily Female Cast", isAdult: false },
  { name: "Primarily Male Cast", isAdult: false },
  { name: "Primarily Teen Cast", isAdult: false },
  { name: "Prison", isAdult: false },
  { name: "Prostitution", isAdult: true },
  { name: "Proxy Battle", isAdult: false },
  { name: "Psychosexual", isAdult: false },
  { name: "Public Sex", isAdult: true },
  { name: "Puppetry", isAdult: false },
  { name: "Rakugo", isAdult: false },
  { name: "Rape", isAdult: true },
  { name: "Real Robot", isAdult: false },
  { name: "Rehabilitation", isAdult: false },
  { name: "Reincarnation", isAdult: false },
  { name: "Religion", isAdult: false },
  { name: "Rescue", isAdult: false },
  { name: "Restaurant", isAdult: false },
  { name: "Revenge", isAdult: false },
  { name: "Reverse Isekai", isAdult: false },
  { name: "Rimjob", isAdult: true },
  { name: "Robots", isAdult: false },
  { name: "Rock Music", isAdult: false },
  { name: "Rotoscoping", isAdult: false },
  { name: "Royal Affairs", isAdult: false },
  { name: "Rugby", isAdult: false },
  { name: "Rural", isAdult: false },
  { name: "Sadism", isAdult: true },
  { name: "Samurai", isAdult: false },
  { name: "Satire", isAdult: false },
  { name: "Scat", isAdult: true },
  { name: "School", isAdult: false },
  { name: "School Club", isAdult: false },
  { name: "Scissoring", isAdult: true },
  { name: "Scuba Diving", isAdult: false },
  { name: "Seinen", isAdult: false },
  { name: "Sex Toys", isAdult: true },
  { name: "Shapeshifting", isAdult: false },
  { name: "Shimaidon", isAdult: true },
  { name: "Ships", isAdult: false },
  { name: "Shogi", isAdult: false },
  { name: "Shoujo", isAdult: false },
  { name: "Shounen", isAdult: false },
  { name: "Shrine Maiden", isAdult: false },
  { name: "Single-Page Chapter", isAdult: false },
  { name: "Skateboarding", isAdult: false },
  { name: "Skeleton", isAdult: false },
  { name: "Slapstick", isAdult: false },
  { name: "Slavery", isAdult: false },
  { name: "Snowscape", isAdult: false },
  { name: "Software Development", isAdult: false },
  { name: "Space", isAdult: false },
  { name: "Space Opera", isAdult: false },
  { name: "Spearplay", isAdult: false },
  { name: "Squirting", isAdult: true },
  { name: "Steampunk", isAdult: false },
  { name: "Stop Motion", isAdult: false },
  { name: "Succubus", isAdult: false },
  { name: "Suicide", isAdult: false },
  { name: "Sumata", isAdult: true },
  { name: "Sumo", isAdult: false },
  { name: "Super Power", isAdult: false },
  { name: "Super Robot", isAdult: false },
  { name: "Superhero", isAdult: false },
  { name: "Surfing", isAdult: false },
  { name: "Surreal Comedy", isAdult: false },
  { name: "Survival", isAdult: false },
  { name: "Swapping ", isAdult: true },
  { name: "Sweat", isAdult: true },
  { name: "Swimming", isAdult: false },
  { name: "Swordplay", isAdult: false },
  { name: "Table Tennis", isAdult: false },
  { name: "Tanks", isAdult: false },
  { name: "Tanned Skin", isAdult: false },
  { name: "Teacher", isAdult: false },
  { name: "Teens' Love", isAdult: false },
  { name: "Tennis", isAdult: false },
  { name: "Tentacles", isAdult: true },
  { name: "Terrorism", isAdult: false },
  { name: "Threesome", isAdult: true },
  { name: "Time Loop", isAdult: false },
  { name: "Time Manipulation", isAdult: false },
  { name: "Time Skip", isAdult: false },
  { name: "Tokusatsu", isAdult: false },
  { name: "Tomboy", isAdult: false },
  { name: "Torture", isAdult: false },
  { name: "Tragedy", isAdult: false },
  { name: "Trains", isAdult: false },
  { name: "Transgender", isAdult: false },
  { name: "Travel", isAdult: false },
  { name: "Triads", isAdult: false },
  { name: "Tsundere", isAdult: false },
  { name: "Twins", isAdult: false },
  { name: "Unrequited Love", isAdult: false },
  { name: "Urban", isAdult: false },
  { name: "Urban Fantasy", isAdult: false },
  { name: "Vampire", isAdult: false },
  { name: "Vertical Video", isAdult: false },
  { name: "Veterinarian", isAdult: false },
  { name: "Video Games", isAdult: false },
  { name: "Vikings", isAdult: false },
  { name: "Villainess", isAdult: false },
  { name: "Virginity", isAdult: true },
  { name: "Virtual World", isAdult: false },
  { name: "Vocal Synth", isAdult: false },
  { name: "Volleyball", isAdult: false },
  { name: "Vore", isAdult: true },
  { name: "Voyeur", isAdult: true },
  { name: "VTuber", isAdult: false },
  { name: "War", isAdult: false },
  { name: "Watersports", isAdult: true },
  { name: "Werewolf", isAdult: false },
  { name: "Wilderness", isAdult: false },
  { name: "Witch", isAdult: false },
  { name: "Work", isAdult: false },
  { name: "Wrestling", isAdult: false },
  { name: "Writing", isAdult: false },
  { name: "Wuxia", isAdult: false },
  { name: "Yakuza", isAdult: false },
  { name: "Yandere", isAdult: false },
  { name: "Youkai", isAdult: false },
  { name: "Yuri", isAdult: false },
  { name: "Zombie", isAdult: false },
  { name: "Zoophilia", isAdult: true },
] as const;
export const studioEnums = [
  { id: 7385, name: "100studio" },
  { id: 6719, name: "1IN" },
  { id: 6373, name: "33 Collective" },
  { id: 7522, name: "3D Co." },
  { id: 6847, name: "5 Inc." },
  { id: 7666, name: "5BRICKS" },
  { id: 6662, name: "717 Studio" },
  { id: 6388, name: "7doc" },
  { id: 4418, name: "8-bit" },
  { id: 171, name: "A Line" },
  { id: 561, name: "A-1 Pictures" },
  { id: 179, name: "A.C.G.T." },
  { id: 7612, name: "A4works" },
  { id: 7540, name: "ABC Animation Studio" },
  { id: 60, name: "Actas" },
  { id: 6583, name: "Adnero" },
  { id: 785, name: "Advance Syakujii" },
  { id: 48, name: "AIC" },
  { id: 88, name: "AIC A.S.T.A." },
  { id: 436, name: "AIC Build" },
  { id: 292, name: "AIC Plus+" },
  { id: 83, name: "AIC Spirits" },
  { id: 425, name: "AIC Takarazuka" },
  { id: 6489, name: "Aisi Animation Studio" },
  { id: 30, name: "Ajiado" },
  { id: 7559, name: "Aka no Joou Kasetsu" },
  { id: 6601, name: "Akatsuki" },
  { id: 7782, name: "Akatsuki Media Studio" },
  { id: 6316, name: "ALBACROW" },
  { id: 7776, name: "AlcedoAlcy" },
  { id: 7035, name: "Alfred Imageworks" },
  { id: 7482, name: "Alke" },
  { id: 7613, name: "AMAKAWAANIMATION" },
  { id: 7651, name: "ame pippin" },
  { id: 878, name: "An DerCen" },
  { id: 7483, name: "Andraft" },
  { id: 7736, name: "Anhui Yingyiyuan Culture Communication" },
  { id: 194, name: "ANIK" },
  { id: 6087, name: "AniMan" },
  { id: 386, name: "Animaruya" },
  { id: 6896, name: "Animate Film" },
  { id: 6111, name: "Animation 21" },
  { id: 7182, name: "Animation 501" },
  { id: 929, name: "Animation Do" },
  { id: 6305, name: "Animation Staff Room" },
  { id: 7621, name: "animation studio42" },
  { id: 7454, name: "Anime Antenna Group" },
  { id: 7455, name: "Anime Antenna Iinkai" },
  { id: 6876, name: "Anime Friend" },
  { id: 971, name: "Anime R" },
  { id: 6875, name: "Anime Room" },
  { id: 7471, name: "Anime Tokyo" },
  { id: 583, name: "Annapuru" },
  { id: 521, name: "Anpro" },
  { id: 7450, name: "Anyzac" },
  { id: 7059, name: "APEX VISION" },
  { id: 7656, name: "Apples" },
  { id: 77, name: "APPP" },
  { id: 6417, name: "AQUA ARIS" },
  { id: 6494, name: "Aqua Entertainment" },
  { id: 7338, name: "Aquastar" },
  { id: 6721, name: "Arc Anime" },
  { id: 7158, name: "ARCUS" },
  { id: 6848, name: "Arect" },
  { id: 38, name: "Arms" },
  { id: 585, name: "Arplants" },
  { id: 8, name: "Artland" },
  { id: 6239, name: "Arvo Animation" },
  { id: 406, name: "Asahi Production" },
  { id: 473, name: "Ascension" },
  { id: 196, name: "Ashi Productions" },
  { id: 6319, name: "ASK Animation Studio" },
  { id: 163, name: "Asread" },
  { id: 7473, name: "ASTROBROS." },
  { id: 6900, name: "Asura Film" },
  { id: 7521, name: "Atelier Bitol" },
  { id: 6830, name: "Atelier Giga" },
  { id: 7735, name: "Atelier Peuplier" },
  { id: 7492, name: "Atelier Platz" },
  { id: 6960, name: "Atelier Pontdarc" },
  { id: 6805, name: "Atoonz" },
  { id: 7700, name: "AtoriE" },
  { id: 7793, name: "Atra" },
  { id: 6090, name: "Aubec" },
  { id: 7757, name: "Aura Studio" },
  { id: 6924, name: "Aurora" },
  { id: 7731, name: "Axis" },
  { id: 6542, name: "Axis Studios" },
  { id: 6108, name: "AXsiZ" },
  { id: 907, name: "AYCO" },
  { id: 6910, name: "Azeta Pictures" },
  { id: 6485, name: "B.CMAY PICTURES" },
  { id: 7324, name: "B.Cool Studio" },
  { id: 6177, name: "B&T" },
  { id: 6728, name: "BAKKEN RECORD" },
  { id: 6116, name: "Bandai Namco Pictures" },
  { id: 59, name: "Beat Frog" },
  { id: 7333, name: "Bebow" },
  { id: 322, name: "Bee Media" },
  { id: 5, name: "Bee Train" },
  { id: 458, name: "Beijing Sharaku Art" },
  { id: 7741, name: "Bells&Whistles" },
  { id: 7688, name: "BENTEN Film" },
  { id: 6838, name: "BETOBE" },
  { id: 7006, name: "Bibury Animation CG" },
  { id: 6180, name: "Bibury Animation Studios" },
  { id: 7681, name: "Big Bang" },
  { id: 6380, name: "BigBigSun" },
  { id: 6138, name: "BLADE" },
  { id: 6376, name: "Blaze Studio" },
  { id: 445, name: "Bliss Pictures" },
  { id: 7133, name: "Block 12" },
  { id: 6918, name: "BlueArc Animation Studio" },
  { id: 6541, name: "BONEDD" },
  { id: 4, name: "bones" },
  { id: 7585, name: "bones film" },
  { id: 6928, name: "BooKong Culture" },
  { id: 6085, name: "BOOTLEG" },
  { id: 6556, name: "Boruntong" },
  { id: 6131, name: "Bouncy" },
  { id: 7346, name: "Boundary" },
  { id: 112, name: "Brain's Base" },
  { id: 6858, name: "BREAKBOTTLE" },
  { id: 397, name: "Bridge" },
  { id: 7417, name: "Bright Studio" },
  { id: 6300, name: "Buemon" },
  { id: 7348, name: "BUG FILMS" },
  { id: 6448, name: "Build Dream" },
  { id: 6128, name: "Bunny Walker" },
  { id: 6934, name: "Burning Animation" },
  { id: 7696, name: "Buyuu" },
  { id: 6519, name: "BYMENT" },
  { id: 7304, name: "Bytehoo" },
  { id: 6074, name: "C-Station" },
  { id: 7544, name: "C&S Production" },
  { id: 6052, name: "C2C" },
  { id: 6459, name: "CALF" },
  { id: 7477, name: "Campfire Aniworks" },
  { id: 7797, name: "Cannon Code" },
  { id: 6791, name: "Cartoon Saloon" },
  { id: 6232, name: "CCTV Animation" },
  { id: 6481, name: "CG Year" },
  { id: 6628, name: "CGCG Studio Inc." },
  { id: 462, name: "Chaos Project" },
  { id: 7112, name: "Character Plan" },
  { id: 6598, name: "Charming Fox Animation" },
  { id: 6874, name: "Children's Corner" },
  { id: 6311, name: "Children's Playground Entertainment" },
  { id: 6099, name: "CHIPPAI" },
  { id: 7479, name: "Chiptune" },
  { id: 6935, name: "Chirying Culture" },
  { id: 6872, name: "Choirock" },
  { id: 6971, name: "Chongliyuhua" },
  { id: 6320, name: "Chongzhuo Animation" },
  { id: 6653, name: "CHOSEN" },
  { id: 7495, name: "Chuangpu Animation Studio" },
  { id: 401, name: "ChuChu" },
  { id: 6849, name: "Cinepix" },
  { id: 7258, name: "Circus Production" },
  { id: 6400, name: "CLAP" },
  { id: 6342, name: "Cloud Art" },
  { id: 7294, name: "CLOUDHEARTS" },
  { id: 6222, name: "CloverWorks" },
  { id: 7049, name: "CMC Media" },
  { id: 6747, name: "Cocktail Media" },
  { id: 6338, name: "Coco Cartoon" },
  { id: 6979, name: "Coco Legends" },
  { id: 325, name: "Code" },
  { id: 519, name: "Collaboration Works" },
  { id: 6321, name: "Colored Pencil Animation" },
  { id: 6867, name: "Colored Pencil Animation Japan" },
  { id: 6335, name: "Coloroom Pictures" },
  { id: 6702, name: "Comic Animation" },
  { id: 291, name: "CoMix Wave" },
  { id: 7263, name: "CompTown" },
  { id: 957, name: "CONNECT" },
  { id: 7128, name: "Contrail" },
  { id: 821, name: "Cotton Doll" },
  { id: 7791, name: "Creadom8" },
  { id: 6404, name: "Creative Bridge" },
  { id: 7502, name: "Creative House Pocket" },
  { id: 6723, name: "Creative Power Entertaining" },
  { id: 6613, name: "Creators Dot Com" },
  { id: 6072, name: "Creators in Pack" },
  { id: 7607, name: "Crew Cell" },
  { id: 6491, name: "Crius Animation" },
  { id: 7693, name: "CUE" },
  { id: 6734, name: "Cyclone Graphics" },
  { id: 6182, name: "CygamesPictures" },
  { id: 7805, name: "Cypic" },
  { id: 7570, name: "D & D Pictures" },
  { id: 6471, name: "D.ROCK-ART" },
  { id: 6913, name: "D’ART Shtajio" },
  { id: 7136, name: "d00r works" },
  { id: 7228, name: "Da Yu" },
  { id: 7798, name: "Daily Plan.net" },
  { id: 6537, name: "Dancing CG Studio" },
  { id: 6521, name: "Dangun Pictures" },
  { id: 7698, name: "Datama Film" },
  { id: 39, name: "Daume" },
  { id: 287, name: "David Production" },
  { id: 6911, name: "Dawn Picture" },
  { id: 7283, name: "Daysview Animation" },
  { id: 6504, name: "Dazzling Star" },
  { id: 6505, name: "DC Impression Vision" },
  { id: 7730, name: "Deck" },
  { id: 7268, name: "Dejavu Media" },
  { id: 6656, name: "Delight Animation" },
  { id: 486, name: "Digital Frontier" },
  { id: 51, name: "diomedéa" },
  { id: 6379, name: "Djinn Power" },
  { id: 276, name: "DLE" },
  { id: 6413, name: "DMM.futureworks" },
  { id: 7376, name: "DNA" },
  { id: 95, name: "Doga Kobo" },
  { id: 479, name: "DOGA Productions" },
  { id: 7717, name: "DOLESS" },
  { id: 6496, name: "domerica" },
  { id: 7746, name: "Doraku" },
  { id: 7649, name: "Dou-Raku" },
  { id: 7789, name: "Double Eagle" },
  { id: 6776, name: "Doumu Animation" },
  { id: 6467, name: "DRAWIZ" },
  { id: 399, name: "Dream Force" },
  { id: 6514, name: "Dreambox Studio" },
  { id: 6289, name: "Drive" },
  { id: 7135, name: "Duoling Cartoon" },
  { id: 7573, name: "Durandal" },
  { id: 6446, name: "Durufix" },
  { id: 7617, name: "Dyna Method" },
  { id: 6710, name: "E-DEHI Animation Studio" },
  { id: 154, name: "E&G Films" },
  { id: 7706, name: "Eallin" },
  { id: 6634, name: "East Fish Studio" },
  { id: 258, name: "Echo" },
  { id: 6106, name: "EDGE" },
  { id: 6127, name: "EGG FIRM" },
  { id: 7799, name: "Electric Circus" },
  { id: 6733, name: "Elias" },
  { id: 7352, name: "Elite Animation" },
  { id: 6125, name: "EMT Squared" },
  { id: 354, name: "Encourage Films" },
  { id: 6292, name: "ENGI" },
  { id: 7626, name: "Ensak Entertainment" },
  { id: 392, name: "Enterbrain" },
  { id: 6901, name: "entity" },
  { id: 7440, name: "EOTA" },
  { id: 6732, name: "Escape Velocity Animation" },
  { id: 567, name: "Ether Kitten" },
  { id: 7372, name: "evg" },
  { id: 7742, name: "EVOLROAR" },
  { id: 6957, name: "EXNOA" },
  { id: 6639, name: "exsa" },
  { id: 7017, name: "Fairy Tale Co." },
  { id: 7111, name: "Fantasier Animation" },
  { id: 7196, name: "Fantawild Animation" },
  { id: 866, name: "Fanworks" },
  { id: 6588, name: "Fast Snail" },
  { id: 6582, name: "Fatchi Moxie Studio" },
  { id: 91, name: "feel." },
  { id: 6126, name: "Felix Film" },
  { id: 6959, name: "Feng Donghua Culture" },
  { id: 7272, name: "Fengyun Animation" },
  { id: 6381, name: "FENZ" },
  { id: 7244, name: "Fever Creations" },
  { id: 6528, name: "FILMKO" },
  { id: 6363, name: "FILMONY" },
  { id: 7425, name: "Fishing Cat Culture" },
  { id: 6828, name: "FLAGSHIP LINE" },
  { id: 6687, name: "FLAT STUDIO" },
  { id: 6907, name: "Flavors Soft" },
  { id: 7064, name: "Flint Sugar" },
  { id: 6162, name: "Foch" },
  { id: 7371, name: "Folium" },
  { id: 6527, name: "Forest Hunting One" },
  { id: 6436, name: "Fortes" },
  { id: 6591, name: "Friends" },
  { id: 69, name: "Front Line" },
  { id: 7185, name: "Frontier One" },
  { id: 7369, name: "Fugaku" },
  { id: 7662, name: "Fun Flux Entertainment" },
  { id: 7448, name: "Fun Media" },
  { id: 7640, name: "FUNNY MOVIE" },
  { id: 7792, name: "FuRyu Pictures" },
  { id: 6290, name: "G-angle" },
  { id: 6866, name: "G-lam" },
  { id: 6130, name: "G.CMay Animation & Film" },
  { id: 7413, name: "G.S. Pictures Animation" },
  { id: 131, name: "G&G Entertainment" },
  { id: 7516, name: "GA-CREW" },
  { id: 6122, name: "Gaina" },
  { id: 6, name: "Gainax" },
  { id: 6295, name: "GAINAX Kyoto" },
  { id: 7288, name: "Gale" },
  { id: 6793, name: "Gambit" },
  { id: 7740, name: "Garage Film" },
  { id: 6546, name: "GARDEN" },
  { id: 7514, name: "GEAR STUDIO" },
  { id: 6216, name: "GEEKTOYS" },
  { id: 6405, name: "Geidai Animation" },
  { id: 7284, name: "Gekkou" },
  { id: 7322, name: "Gen Long Culture" },
  { id: 6142, name: "Geno Studio" },
  { id: 6712, name: "Gift-o’-Animation" },
  { id: 6703, name: "Ginga Teikoku" },
  { id: 176, name: "Ginga Ya" },
  { id: 309, name: "GoHands" },
  { id: 6581, name: "Gokuusha" },
  { id: 6092, name: "GOLD BEAR" },
  { id: 6575, name: "Gold Valley Films" },
  { id: 3, name: "GONZO" },
  { id: 6440, name: "Gosay Studio" },
  { id: 829, name: "GRAPH77" },
  { id: 894, name: "Graphinica" },
  { id: 7795, name: "Grass" },
  { id: 7261, name: "Gravity Well" },
  { id: 6522, name: "Great Dreams Cartoon" },
  { id: 7664, name: "Green Box" },
  { id: 152, name: "Green Bunny" },
  { id: 6386, name: "Green Monster Team" },
  { id: 6844, name: "Green Ooita" },
  { id: 7325, name: "Green Planet Studio" },
  { id: 7639, name: "Greenleaf Animation" },
  { id: 6458, name: "Grimae Animation Studio" },
  { id: 6985, name: "GritWorld" },
  { id: 86, name: "Group TAC" },
  { id: 391, name: "Grouper Production" },
  { id: 6326, name: "Gudong Animation Studio" },
  { id: 34, name: "Hal Film Maker" },
  { id: 811, name: "Hangzhou Shimei Pictures" },
  { id: 7749, name: "Hanho Heung-Up" },
  { id: 6492, name: "Hanna Pictures" },
  { id: 6140, name: "Haoliners Animation" },
  { id: 7691, name: "HAPPYMAN♥" },
  { id: 6372, name: "happyproject" },
  { id: 7066, name: "Hayabusa Film" },
  { id: 7048, name: "He Zhou Culture" },
  { id: 7215, name: "Heart & Soul Animation" },
  { id: 6564, name: "Heartbit" },
  { id: 367, name: "Heewon Entertainment" },
  { id: 7031, name: "Hero" },
  { id: 527, name: "Higa Brothers Production" },
  { id: 6083, name: "HiLLS" },
  { id: 6645, name: "HM Heros" },
  { id: 6426, name: "HMCH" },
  { id: 6578, name: "Hong Li Animation Studios" },
  { id: 6560, name: "Hong Ying Animation" },
  { id: 7301, name: "Honglu Technology" },
  { id: 346, name: "Hoods Entertainment" },
  { id: 6360, name: "HORNETS" },
  { id: 268, name: "Hot Bear" },
  { id: 723, name: "Hotline" },
  { id: 7615, name: "HS PICTURES" },
  { id: 7061, name: "Hua Dream" },
  { id: 6941, name: "HuaMei Animation" },
  { id: 7054, name: "Hui Guang Studio" },
  { id: 6850, name: "Hurray!" },
  { id: 6692, name: "Hyoin Entertainment" },
  { id: 7387, name: "I was a Ballerina" },
  { id: 389, name: "I-move" },
  { id: 6452, name: "I.G Zwei" },
  { id: 375, name: "I.Toon" },
  { id: 7556, name: "I&S Factory" },
  { id: 6701, name: "Ichigo Animation" },
  { id: 7631, name: "Iconix Entertainment" },
  { id: 6525, name: "IDEOMOTOR" },
  { id: 6348, name: "iDRAGONS Creative Studio" },
  { id: 6543, name: "IDREAM Entertainment" },
  { id: 7319, name: "Ijigen TOKYO" },
  { id: 7571, name: "IKEAnimations" },
  { id: 7633, name: "IKIF+" },
  { id: 7582, name: "ILCASHIPS" },
  { id: 7531, name: "Imageworks Studio" },
  { id: 7367, name: "IMAGICA DIGITALSCAPE" },
  { id: 75, name: "Imagin" },
  { id: 6349, name: "Imagineer" },
  { id: 6826, name: "INDIVISION" },
  { id: 6635, name: "Infinity Vision" },
  { id: 7684, name: "INREALITY" },
  { id: 7438, name: "INTERFACEDOGS" },
  { id: 421, name: "International Digital Artist" },
  { id: 6296, name: "Ishimori Entertainment" },
  { id: 6420, name: "Issen" },
  { id: 6722, name: "ITS CARTOON" },
  { id: 7269, name: "j-cube" },
  { id: 7, name: "J.C.STAFF" },
  { id: 222, name: "Jade Animation" },
  { id: 7086, name: "Jaggard" },
  { id: 257, name: "Jam" },
  { id: 6865, name: "Japan Taps" },
  { id: 6465, name: "JCF" },
  { id: 6927, name: "Jiang Toon Animation" },
  { id: 6825, name: "Jichitai Anime" },
  { id: 6992, name: "Jihou Eigasha" },
  { id: 444, name: "Jinni's Animation Studio" },
  { id: 7198, name: "Jintu Pictures" },
  { id: 7727, name: "JIUBAO ANIMATION" },
  { id: 6493, name: "JJJoy Animation Studios" },
  { id: 336, name: "JM animation" },
  { id: 6507, name: "Joicy Studio" },
  { id: 755, name: "Jumondou" },
  { id: 7794, name: "JUVENAGE" },
  { id: 6486, name: "K.PICTURES" },
  { id: 7363, name: "Kaca Entertainment" },
  { id: 7632, name: "Kachigarasu" },
  { id: 7665, name: "Kagome Company" },
  { id: 437, name: "Kamikaze Douga" },
  { id: 330, name: "Kanaban Graphics" },
  { id: 288, name: "Kaname Production" },
  { id: 348, name: "Kawamoto Productions" },
  { id: 7499, name: "Ke Yue Xue Zi" },
  { id: 6694, name: "Keika Co. Ltd." },
  { id: 7542, name: "Keyaki Works" },
  { id: 449, name: "KeyEast" },
  { id: 7630, name: "Keyring" },
  { id: 7041, name: "Kigumi" },
  { id: 7381, name: "KIKO" },
  { id: 290, name: "Kinema Citrus" },
  { id: 6094, name: "King Bee" },
  { id: 477, name: "Kino Production" },
  { id: 7784, name: "Kinseijin Firm" },
  { id: 6661, name: "KIO STUDIO" },
  { id: 7085, name: "kitsutsuki" },
  { id: 6952, name: "Kobe Design University" },
  { id: 241, name: "Koei" },
  { id: 275, name: "Kojiro Shishido Animation Works" },
  { id: 7494, name: "KONAMI animation" },
  { id: 7618, name: "Konyoshi" },
  { id: 7447, name: "KUAIYING" },
  { id: 7605, name: "Kumarba" },
  { id: 6843, name: "Kun Animation & Comic" },
  { id: 7057, name: "Kungfufrog Animation" },
  { id: 377, name: "Kuri Jikken Manga Kobo" },
  { id: 2, name: "Kyoto Animation" },
  { id: 7720, name: "Kyowa " },
  { id: 6449, name: "l-a-unch・BOX" },
  { id: 6176, name: "L² Studio" },
  { id: 563, name: "LandQ studios" },
  { id: 529, name: "Lapis" },
  { id: 896, name: "Larx Entertainment" },
  { id: 6075, name: "Lay-duce" },
  { id: 456, name: "Lerche" },
  { id: 7225, name: "Liber" },
  { id: 6410, name: "Liberty Animation Studio" },
  { id: 839, name: "LIDENFILMS" },
  { id: 6982, name: "LIDENFILMS Kyoto Studio" },
  { id: 6966, name: "Lifework" },
  { id: 6266, name: "Light Chaser Animation" },
  { id: 7446, name: "Liliyabi" },
  { id: 7625, name: "Lingke Culture" },
  { id: 6585, name: "Lingsanwu Animation" },
  { id: 7610, name: "LinQ" },
  { id: 6968, name: "Live2D Creative Studio" },
  { id: 6649, name: "Liyu Culture" },
  { id: 7572, name: "LOCUS Animation" },
  { id: 823, name: "Lune Pictures" },
  { id: 6383, name: "LX Animation Studio" },
  { id: 463, name: "M.S.C" },
  { id: 430, name: "Mad Box" },
  { id: 11, name: "MADHOUSE" },
  { id: 6351, name: "Magia Doraglier" },
  { id: 207, name: "Magic Bus" },
  { id: 7518, name: "Magic Lantern Film" },
  { id: 6954, name: "MagiDian" },
  { id: 6394, name: "Magilm Pictures" },
  { id: 6288, name: "Maho Film" },
  { id: 7467, name: "Mainichi Eigasha" },
  { id: 767, name: "Majin" },
  { id: 6443, name: "Makaria" },
  { id: 6495, name: "MAKING ANIMATION" },
  { id: 6370, name: "MANAA ANIMATION" },
  { id: 7422, name: "Mandrill Picture Corp" },
  { id: 32, name: "Manglobe" },
  { id: 6794, name: "ManHoo Culture" },
  { id: 7045, name: "Maple Toon" },
  { id: 569, name: "MAPPA" },
  { id: 7379, name: "maroyaka" },
  { id: 7629, name: "MARU animation" },
  { id: 320, name: "Maru Production" },
  { id: 553, name: "Marvy Jack" },
  { id: 424, name: "Mary Jane" },
  { id: 6324, name: "Maten Animation" },
  { id: 7519, name: "matlity" },
  { id: 6931, name: "Max-World" },
  { id: 6457, name: "Meditation With a Pencil" },
  { id: 6923, name: "Medo" },
  { id: 7587, name: "Meltdown" },
  { id: 7470, name: "MI" },
  { id: 6540, name: "Mifan Animation" },
  { id: 7329, name: "Mili Digital" },
  { id: 6344, name: "Mili Pictures" },
  { id: 25, name: "Milky Animation Label" },
  { id: 6073, name: "Millepensee" },
  { id: 442, name: "Minami Machi Bugyousho" },
  { id: 7280, name: "Mind Wind Studio" },
  { id: 7589, name: "Miota Studio" },
  { id: 6123, name: "Mirai Film" },
  { id: 394, name: "Misseri Studio" },
  { id: 6084, name: "Mitsu" },
  { id: 7496, name: "Miyu Productions" },
  { id: 6795, name: "MMT" },
  { id: 7374, name: "mobanimation" },
  { id: 637, name: "Möbius Tone" },
  { id: 7474, name: "MOE" },
  { id: 7046, name: "MOJO" },
  { id: 6307, name: "Monster's Egg" },
  { id: 7119, name: "MontBlanc Pictures" },
  { id: 6624, name: "MooGoo" },
  { id: 54, name: "Mook Animation" },
  { id: 6483, name: "Mote Stop-Motion Animation" },
  { id: 7552, name: "Motherland Entertainment" },
  { id: 6470, name: "Motion Magic" },
  { id: 7724, name: "Mouse" },
  { id: 6752, name: "Mousou Senka" },
  { id: 7040, name: "Mu Animation Studio" },
  { id: 6859, name: "Musashino Art University" },
  { id: 68, name: "Mushi Production" },
  { id: 7788, name: "MUSUHI" },
  { id: 533, name: "N&G Production" },
  { id: 7614, name: "Nagomi" },
  { id: 6658, name: "Nakamura Production" },
  { id: 6532, name: "NAMU Animation" },
  { id: 7489, name: "nanibito " },
  { id: 951, name: "NAZ" },
  { id: 6120, name: "Neft Film" },
  { id: 7364, name: "Netflix Anime Creators' Base" },
  { id: 6854, name: "NewGeneration" },
  { id: 7683, name: "NEWON" },
  { id: 819, name: "NEXT Animation Studio" },
  { id: 7377, name: "Next Media Animation" },
  { id: 852, name: "Nexus" },
  { id: 7701, name: "NICHICALINE" },
  { id: 7785, name: "Ningbo Minhe Film And Television Animation" },
  { id: 22, name: "Nippon Animation" },
  { id: 7672, name: "Nishiko Production" },
  { id: 7202, name: "No Side" },
  { id: 7106, name: "NOKID" },
  { id: 70, name: "Nomad" },
  { id: 6813, name: "Noovo Inc." },
  { id: 7728, name: "NOTHING NEW" },
  { id: 7277, name: "Number 19 Animation" },
  { id: 6148, name: "NUT" },
  { id: 7721, name: "Nyan Pollution-ω-" },
  { id: 6989, name: "Observatory Animation" },
  { id: 7457, name: "Ocon Studios" },
  { id: 6760, name: "October Media" },
  { id: 6517, name: "ODDJOB" },
  { id: 6962, name: "Office 8-ban" },
  { id: 429, name: "Office AO" },
  { id: 6076, name: "office DCI" },
  { id: 481, name: "Office Take Off" },
  { id: 6317, name: "Office Takeout" },
  { id: 234, name: "Oh! Production" },
  { id: 6314, name: "Okuruto Noboru" },
  { id: 28, name: "OLM" },
  { id: 7767, name: "Onakama" },
  { id: 6325, name: "One & All Animation Studio" },
  { id: 6554, name: "One Punch" },
  { id: 6397, name: "Opera House" },
  { id: 6077, name: "Orange" },
  { id: 7423, name: "Orcen" },
  { id: 334, name: "Ordet" },
  { id: 7110, name: "ORENDA" },
  { id: 6476, name: "Oriental Creative Color" },
  { id: 7779, name: "Origin Animation" },
  { id: 7052, name: "Origin Chasing" },
  { id: 6660, name: "Original Dream" },
  { id: 6484, name: "Original Force" },
  { id: 6932, name: "Original Heart" },
  { id: 831, name: "Otogi Production" },
  { id: 6714, name: "OTOIRO" },
  { id: 6912, name: "OUTLINE" },
  { id: 7601, name: "OutSide Directors Company" },
  { id: 361, name: "Oxybot" },
  { id: 6751, name: "OZ" },
  { id: 395, name: "OZ Inc." },
  { id: 132, name: "P.A.WORKS" },
  { id: 6711, name: "P.I.C.S." },
  { id: 6921, name: "Pai Naodai Animation" },
  { id: 6657, name: "Painted Edge" },
  { id: 6929, name: "Paintfree" },
  { id: 6482, name: "Painting Dream" },
  { id: 455, name: "Palm Studio" },
  { id: 6407, name: "Pancake" },
  { id: 373, name: "Panda Kojo" },
  { id: 7267, name: "Panda Tower Studio" },
  { id: 6533, name: "Pandanium" },
  { id: 226, name: "Panmedia" },
  { id: 7275, name: "PAPA " },
  { id: 6323, name: "Paper Plane Animation Studio" },
  { id: 862, name: "Pashmina" },
  { id: 7033, name: "Pass Media" },
  { id: 7043, name: "Passion Paint Animation" },
  { id: 911, name: "Passione" },
  { id: 413, name: "Pastel" },
  { id: 6318, name: "Pb Animation" },
  { id: 6518, name: "Peak Hunt" },
  { id: 7602, name: "Perfect Kunpeng" },
  { id: 6798, name: "pH Studio" },
  { id: 329, name: "Phoenix Entertainment" },
  { id: 6820, name: "Picsys" },
  { id: 78, name: "Picture Magic" },
  { id: 7604, name: "Pierce Visual Works" },
  { id: 7517, name: "PIERROT FILMS" },
  { id: 6419, name: "Pili International Multimedia" },
  { id: 6103, name: "PINE JAM" },
  { id: 7339, name: "Pingo Entertainment" },
  { id: 45, name: "Pink Pineapple" },
  { id: 6455, name: "Piso Studio" },
  { id: 175, name: "Planet" },
  { id: 6350, name: "Planet Cartoon" },
  { id: 7628, name: "Planet Studios" },
  { id: 6149, name: "Platinum Vision" },
  { id: 7093, name: "Plott" },
  { id: 107, name: "Plum" },
  { id: 7574, name: "Point Five Creations" },
  { id: 7456, name: "Point Pictures" },
  { id: 6943, name: "Poly Animation" },
  { id: 6067, name: "POLYGON PICTURES" },
  { id: 931, name: "Poncotan" },
  { id: 365, name: "PoRO" },
  { id: 6134, name: "PoRO petit" },
  { id: 448, name: "Postgal Workshop" },
  { id: 7452, name: "PPURI" },
  { id: 753, name: "PRA" },
  { id: 6499, name: "Prhythm Vision" },
  { id: 347, name: "PrimeTime" },
  { id: 6596, name: "Procen Studio" },
  { id: 6737, name: "Production +h" },
  { id: 10, name: "Production I.G" },
  { id: 4420, name: "Production IMS" },
  { id: 7638, name: "Production Kai" },
  { id: 6672, name: "Production Reed" },
  { id: 4399, name: "project No.9" },
  { id: 7008, name: "Project Studio Q" },
  { id: 7206, name: "Project Team Argos" },
  { id: 7682, name: "Psyde Kick Studio" },
  { id: 6345, name: "Public & Basic" },
  { id: 7424, name: "Pure Arts" },
  { id: 343, name: "Puzzle Animation" },
  { id: 6718, name: "Qianqi Cartoon" },
  { id: 7305, name: "Qingxiang" },
  { id: 6832, name: "Qiying Animation" },
  { id: 6547, name: "Qiyuan Yinghua" },
  { id: 6970, name: "qmotri" },
  { id: 7002, name: "Quad" },
  { id: 6150, name: "Qualia Animation" },
  { id: 6627, name: "Qubic Pictures" },
  { id: 6599, name: "Quebico" },
  { id: 6093, name: "Queen Bee" },
  { id: 7652, name: "R11R" },
  { id: 6946, name: "Rabbit Gate" },
  { id: 81, name: "Radix" },
  { id: 7165, name: "Rainbridge Animation" },
  { id: 7667, name: "Raiose" },
  { id: 6343, name: "Rastar" },
  { id: 6086, name: "REALTHING" },
  { id: 6535, name: "Realwood Studios" },
  { id: 7050, name: "Red Dog Culture House" },
  { id: 6577, name: "Red Whale Studios" },
  { id: 7337, name: "REGARO" },
  { id: 6780, name: "Reike Eyes Animation" },
  { id: 7504, name: "REILS" },
  { id: 7611, name: "REIRS" },
  { id: 6217, name: "REVOROOT" },
  { id: 253, name: "Rikuentai" },
  { id: 6082, name: "Rising Force" },
  { id: 249, name: "Robot" },
  { id: 6479, name: "Rocen" },
  { id: 7745, name: "ROCK'N ROLL MOUNTAIN" },
  { id: 7660, name: "Rockwell Eyes" },
  { id: 7475, name: "ROLL2" },
  { id: 7539, name: "Rouseact" },
  { id: 446, name: "RTHK" },
  { id: 6977, name: "Ruichen Pictures" },
  { id: 6475, name: "Ruo Hong Culture" },
  { id: 7620, name: "Ryuu M's" },
  { id: 6857, name: "S.o.K" },
  { id: 7412, name: "Saber Project" },
  { id: 7524, name: "Saber Works" },
  { id: 7432, name: "SAFEHOUSE" },
  { id: 6586, name: "Saiji" },
  { id: 765, name: "Sakura Create" },
  { id: 6515, name: "Sakura Eiga" },
  { id: 6352, name: "SAKURAPRIN Animation" },
  { id: 6792, name: "SAMG Animation" },
  { id: 6958, name: "Sanctuary" },
  { id: 6884, name: "Sansan Studio" },
  { id: 537, name: "SANZIGEN" },
  { id: 41, name: "Satelight" },
  { id: 6145, name: "Science SARU" },
  { id: 7095, name: "Scooter Films" },
  { id: 7796, name: "SEAGULL" },
  { id: 7102, name: "Seenewtall Animation Studio" },
  { id: 6144, name: "Selfish" },
  { id: 7581, name: "Senju Kobo" },
  { id: 7468, name: "Seoul Animation" },
  { id: 6461, name: "Seoul Movie" },
  { id: 541, name: "Seven" },
  { id: 35, name: "Seven Arcs" },
  { id: 6322, name: "Seven Stone Entertainment" },
  { id: 44, name: "Shaft" },
  { id: 471, name: "Shanghai Animation Film Studio" },
  { id: 7498, name: "Shanghai Longcang Cultural Creative Company" },
  { id: 7326, name: "Shanghai Phantom Animation" },
  { id: 7298, name: "Shangshui Original" },
  { id: 6333, name: "Sharefun Studio" },
  { id: 7047, name: "Shenfan Animation" },
  { id: 7083, name: "Sheng Guang Qishi Tuan" },
  { id: 6392, name: "Shengying Animation" },
  { id: 7116, name: "Shenman Entertainment" },
  { id: 7328, name: "Shi Qi Yu Mo" },
  { id: 247, name: "Shin-Ei Animation" },
  { id: 485, name: "Shinwon Productions" },
  { id: 7213, name: "Shion" },
  { id: 235, name: "Shirogumi" },
  { id: 7553, name: "Shobi University" },
  { id: 6071, name: "Shuka" },
  { id: 7120, name: "SIDO" },
  { id: 6101, name: "Signal.MD" },
  { id: 7342, name: "SIGNIF" },
  { id: 300, name: "SILVER LINK." },
  { id: 6988, name: "Simage Animation" },
  { id: 6659, name: "SJYNEXCUS" },
  { id: 6531, name: "Sky Dog" },
  { id: 7270, name: "Skyloong" },
  { id: 7773, name: "SLEE PRODUCTION" },
  { id: 6724, name: "SMG Pictures" },
  { id: 6544, name: "Soda Bear Animation" },
  { id: 7690, name: "SOFA STUDIO" },
  { id: 7505, name: "Soigne" },
  { id: 7378, name: "soket" },
  { id: 6827, name: "Sorajima Studio" },
  { id: 7654, name: "SOUL CREATIVE" },
  { id: 7327, name: "Soul Stone Animation Studio" },
  { id: 7100, name: "Soular Animation" },
  { id: 364, name: "Sovat Theater" },
  { id: 6478, name: "Soyep" },
  { id: 6337, name: "Space Neko Company" },
  { id: 7323, name: "Space Shell" },
  { id: 6393, name: "Sparkly Key Animation" },
  { id: 6353, name: "Speed" },
  { id: 6500, name: "Spell Bound" },
  { id: 6967, name: "Spooky graphic" },
  { id: 6456, name: "Sprite Animation Studios" },
  { id: 7375, name: "Square Pictures" },
  { id: 6512, name: "STANDTOWER" },
  { id: 7107, name: "Staple Entertainment" },
  { id: 6835, name: "Star Hunter Animation" },
  { id: 7278, name: "Steam Works" },
  { id: 7453, name: "Stellation" },
  { id: 7034, name: "STEREOTYPE Inc." },
  { id: 6950, name: "Story Effect" },
  { id: 6852, name: "Studio 1st" },
  { id: 6069, name: "Studio 3Hz" },
  { id: 13, name: "Studio 4°C" },
  { id: 7154, name: "STUDIO 6'oN" },
  { id: 7200, name: "Studio 8 Dogs" },
  { id: 7408, name: "Studio Add" },
  { id: 7520, name: "studio ALBLE" },
  { id: 7738, name: "studio ALL GREEN" },
  { id: 298, name: "Studio Anima" },
  { id: 7772, name: "Studio Artegg" },
  { id: 7774, name: "Studio BAZOOKA" },
  { id: 6309, name: "Studio Bind" },
  { id: 478, name: "Studio Blanc" },
  { id: 338, name: "Studio Bogey" },
  { id: 6567, name: "studio CANDY BOX" },
  { id: 555, name: "Studio Chizu" },
  { id: 7725, name: "Studio Chromato" },
  { id: 7606, name: "Studio Clutch" },
  { id: 4419, name: "Studio Colorido" },
  { id: 126, name: "Studio Comet" },
  { id: 6301, name: "Studio Crocodile" },
  { id: 6797, name: "studio daisy" },
  { id: 37, name: "Studio DEEN" },
  { id: 7674, name: "STUDIO DOTOU" },
  { id: 7762, name: "STUDIO EEK" },
  { id: 409, name: "Studio Egg" },
  { id: 7503, name: "STUDIO EIGHTCOLORS" },
  { id: 6498, name: "Studio elle" },
  { id: 24, name: "Studio Fantasia" },
  { id: 93, name: "Studio Flag" },
  { id: 7383, name: "Studio Fusion" },
  { id: 4271, name: "Studio G-1Neo" },
  { id: 36, name: "Studio Gallop" },
  { id: 6705, name: "Studio Gazelle" },
  { id: 21, name: "Studio Ghibli" },
  { id: 7569, name: "Studio Giants" },
  { id: 6568, name: "Studio Gohan" },
  { id: 6358, name: "Studio Goindol" },
  { id: 418, name: "Studio Gokumi" },
  { id: 497, name: "Studio Gram" },
  { id: 6291, name: "Studio Guts" },
  { id: 6840, name: "studio hb" },
  { id: 101, name: "Studio Hibari" },
  { id: 6298, name: "Studio Houkiboshi" },
  { id: 7558, name: "Studio HUIT" },
  { id: 117, name: "Studio Izena" },
  { id: 6589, name: "Studio JEMI" },
  { id: 280, name: "Studio Junio" },
  { id: 937, name: "Studio Kaab" },
  { id: 6754, name: "Studio Kafka" },
  { id: 6312, name: "Studio KAI" },
  { id: 7800, name: "studio keel" },
  { id: 909, name: "Studio Kelmadick" },
  { id: 47, name: "Studio Khara" },
  { id: 256, name: "Studio Kikan" },
  { id: 7546, name: "Studio Kingyoiro" },
  { id: 440, name: "Studio Kuma" },
  { id: 177, name: "Studio Kyuuma" },
  { id: 6391, name: "Studio LAN" },
  { id: 7575, name: "studio LEO" },
  { id: 7199, name: "Studio Lings" },
  { id: 6460, name: "Studio Live" },
  { id: 6983, name: "Studio Look" },
  { id: 6137, name: "Studio M2" },
  { id: 7694, name: "studio maf" },
  { id: 6409, name: "Studio Magara" },
  { id: 7554, name: "Studio Magic Zoo" },
  { id: 7624, name: "Studio MAGICPOT" },
  { id: 7584, name: "Studio Mangosteen" },
  { id: 7579, name: "Studio Marbean" },
  { id: 6524, name: "Studio Massket" },
  { id: 114, name: "Studio Matrix" },
  { id: 6948, name: "Studio Mindo" },
  { id: 7341, name: "Studio Mir" },
  { id: 7018, name: "STUDIO MORIKEN" },
  { id: 6638, name: "studio MOTHER" },
  { id: 487, name: "Studio MWP" },
  { id: 7254, name: "Studio N" },
  { id: 7344, name: "Studio Nanahoshi" },
  { id: 781, name: "Studio NOA" },
  { id: 7515, name: "Studio Outrigger" },
  { id: 6949, name: "Studio OX" },
  { id: 6738, name: "Studio Palette" },
  { id: 7007, name: "Studio Pasa" },
  { id: 299, name: "Studio Pastoral" },
  { id: 1, name: "Studio Pierrot" },
  { id: 7650, name: "STUDIO POLARIS" },
  { id: 7463, name: "STUDIO POLON" },
  { id: 6147, name: "Studio Ponoc" },
  { id: 7671, name: "STUDIO PPURI" },
  { id: 443, name: "Studio PuYUKAI" },
  { id: 7550, name: "Studio Ranmaru" },
  { id: 84, name: "Studio Rikka" },
  { id: 7778, name: "Studio Roomer" },
  { id: 7790, name: "Studio Shelter" },
  { id: 629, name: "Studio Sign" },
  { id: 438, name: "Studio Signal" },
  { id: 6109, name: "Studio Signpost" },
  { id: 6240, name: "Studio Silver" },
  { id: 7220, name: "STUDIO SOTA" },
  { id: 7577, name: "studio Stellation" },
  { id: 494, name: "Studio Take Off" },
  { id: 6772, name: "Studio Ten Carat" },
  { id: 6829, name: "studio TNT" },
  { id: 210, name: "Studio Tulip" },
  { id: 6526, name: "Studio Tumble" },
  { id: 6814, name: "Studio Ugoki" },
  { id: 404, name: "Studio Unicorn" },
  { id: 7732, name: "studio VOLT" },
  { id: 7400, name: "Studio W.Baba" },
  { id: 412, name: "Studio Wombat" },
  { id: 903, name: "Studio Zealot" },
  { id: 6124, name: "Studio! Cucuri" },
  { id: 7722, name: "studioDOT" },
  { id: 7588, name: "StudioGOONEYS" },
  { id: 549, name: "StudioRF Inc." },
  { id: 7770, name: "SUGARLESS FACTORY" },
  { id: 6566, name: "Sunflowers" },
  { id: 7549, name: "Sunny Gapen" },
  { id: 761, name: "Sunny Side Up" },
  { id: 14, name: "Sunrise" },
  { id: 6573, name: "Sunrise Beyond" },
  { id: 7108, name: "Sunshine Corporation" },
  { id: 6451, name: "Super Normal Studio" },
  { id: 7409, name: "SUPER SUPER" },
  { id: 6315, name: "SUSPENDERS" },
  { id: 7655, name: "Suzume" },
  { id: 434, name: "Synergy Japan" },
  { id: 118, name: "SynergySP" },
  { id: 6509, name: "SYOK Studio" },
  { id: 405, name: "T-REX" },
  { id: 6565, name: "T-UP" },
  { id: 7733, name: "T-ZERO FACTORY" },
  { id: 7394, name: "T.P.O" },
  { id: 6384, name: "Taikong Works" },
  { id: 917, name: "Takahashi Studio" },
  { id: 6686, name: "Take-Y Inc." },
  { id: 939, name: "Tama Production" },
  { id: 388, name: "Tamura Shigeru Studio" },
  { id: 7405, name: "Tang Kirin Culture" },
  { id: 6630, name: "TANOism" },
  { id: 6725, name: "Taomee" },
  { id: 416, name: "TAP" },
  { id: 103, name: "Tatsunoko Production" },
  { id: 7476, name: "Team OneOne" },
  { id: 6412, name: "Team TillDawn" },
  { id: 6414, name: "Team Yamahitsuji" },
  { id: 6246, name: "Tear-Studio" },
  { id: 7022, name: "TEATRO Nishi Tokyo Studio" },
  { id: 7193, name: "TECARAT" },
  { id: 7501, name: "Teddy" },
  { id: 94, name: "Telecom Animation Film" },
  { id: 6788, name: "Ten Tails Animation" },
  { id: 6132, name: "Tengu Kobou" },
  { id: 6141, name: "Tetra" },
  { id: 200, name: "Tezuka Productions" },
  { id: 229, name: "The Answer Studio" },
  { id: 476, name: "The Berich" },
  { id: 6693, name: "The Monk Studios" },
  { id: 6336, name: "The National Film Center Japan" },
  { id: 350, name: "The Village of Marchen" },
  { id: 7044, name: "Thunder River" },
  { id: 7406, name: "Thymos Media" },
  { id: 6468, name: "TIA" },
  { id: 6726, name: "Tiantai Animation" },
  { id: 6425, name: "Tianwen Kadokawa" },
  { id: 7279, name: "Tide Boy" },
  { id: 248, name: "Tin House" },
  { id: 73, name: "TMS Entertainment" },
  { id: 6473, name: "TMX Art" },
  { id: 120, name: "TNK" },
  { id: 7330, name: "to be reused" },
  { id: 18, name: "Toei Animation" },
  { id: 7368, name: "TOHO animation STUDIO" },
  { id: 7659, name: "Tokyo Douga" },
  { id: 122, name: "Tokyo Kids" },
  { id: 6361, name: "Tokyo Movie" },
  { id: 65, name: "Tokyo Movie Shinsha" },
  { id: 6079, name: "Tomovies" },
  { id: 366, name: "Tomoyasu Murata Company" },
  { id: 7541, name: "Tonari Animation" },
  { id: 7702, name: "Toon Harbor Works" },
  { id: 363, name: "Topcraft" },
  { id: 80, name: "Trans Arts" },
  { id: 6536, name: "Transcendence Picture" },
  { id: 6736, name: "Transistor Studio" },
  { id: 7703, name: "Trash Studio" },
  { id: 6396, name: "TRCARTOON" },
  { id: 6501, name: "Tri-Slash" },
  { id: 110, name: "Triangle Staff" },
  { id: 384, name: "Trick Block" },
  { id: 803, name: "TRIGGER" },
  { id: 178, name: "Trilogy Future Studio" },
  { id: 6378, name: "TrioPen Studio" },
  { id: 6068, name: "TROYCA" },
  { id: 6762, name: "Tsubasa Production" },
  { id: 453, name: "Tsuburaya Productions" },
  { id: 390, name: "Tsuchida Productions" },
  { id: 6398, name: "Tsukimidou" },
  { id: 7331, name: "Tsumugi Akita Anime Lab" },
  { id: 7687, name: "Tsumupapa" },
  { id: 6775, name: "TThunDer Animation" },
  { id: 6804, name: "TUBAn" },
  { id: 6853, name: "TWR Entertainment" },
  { id: 6587, name: "Tyhoo CG" },
  { id: 333, name: "TYO Animations" },
  { id: 7634, name: "Type ZERO" },
  { id: 6143, name: "TYPHOON GRAPHICS" },
  { id: 7320, name: "UchuPeople" },
  { id: 43, name: "ufotable" },
  { id: 7382, name: "UNEND" },
  { id: 371, name: "Union Cho" },
  { id: 6651, name: "Unity of Knowledge and Action Animation" },
  { id: 7098, name: "Universal Star Animation" },
  { id: 7073, name: "UOU Studio" },
  { id: 6151, name: "Use me pls" },
  { id: 945, name: "Vasoon Animation" },
  { id: 6889, name: "VCRWORKS" },
  { id: 457, name: "Venet" },
  { id: 7670, name: "VIGORE" },
  { id: 6981, name: "Village Studio" },
  { id: 6558, name: "Visual Flight" },
  { id: 6529, name: "Visual Persistence" },
  { id: 7362, name: "Voil" },
  { id: 7265, name: "Vooz Character System" },
  { id: 7121, name: "Wanhe Huyu" },
  { id: 318, name: "WAO World" },
  { id: 7334, name: "Watanabe Promotion" },
  { id: 7053, name: "Wenzhou Mengbu Anime Design" },
  { id: 6091, name: "WHITE BEAR" },
  { id: 314, name: "WHITE FOX" },
  { id: 6704, name: "White Lily" },
  { id: 6643, name: "White Paper Animation" },
  { id: 396, name: "Wind Under the Wings" },
  { id: 6545, name: "WinSing Animation" },
  { id: 6434, name: "Wired" },
  { id: 858, name: "WIT STUDIO" },
  { id: 6293, name: "Wolf Smoke" },
  { id: 6294, name: "Wolf Smoke Studio" },
  { id: 6416, name: "WolfsBane" },
  { id: 6778, name: "Wonder Cat Animation" },
  { id: 6730, name: "wonderium" },
  { id: 7597, name: "Wonderland" },
  { id: 7013, name: "Wu Zhi Guanying Dongman" },
  { id: 6846, name: "Wulifang Animation" },
  { id: 27, name: "Xebec" },
  { id: 898, name: "Xebec Zwei" },
  { id: 7295, name: "Xiaolan Friends" },
  { id: 7421, name: "Xiaoxiang Pictures" },
  { id: 6845, name: "Xiaoying Feiyang Pictures" },
  { id: 6834, name: "Xing Yi Kai Chen" },
  { id: 6647, name: "Xinglü Animation" },
  { id: 6538, name: "Xiron Animation" },
  { id: 6774, name: "Xiyang Culture" },
  { id: 7419, name: "XMOV" },
  { id: 7399, name: "Xtorm" },
  { id: 6654, name: "Xuni Pictures" },
  { id: 6347, name: "Yamamura Animation, Inc." },
  { id: 7090, name: "YAMATO WORKS" },
  { id: 7091, name: "YAMATOWORKS" },
  { id: 7673, name: "Yamiken" },
  { id: 7286, name: "Yasuda Genshou Studio by Xenotoon" },
  { id: 6435, name: "Year Young Culture" },
  { id: 7189, name: "yell" },
  { id: 308, name: "Yellow Film" },
  { id: 6327, name: "YHKT Entertainment" },
  { id: 6789, name: "Yi Animation" },
  { id: 6385, name: "Yi Chen Animation" },
  { id: 6757, name: "Yinhe Changxing Culture" },
  { id: 6925, name: "Yixiang Culture" },
  { id: 6371, name: "Yostar Pictures" },
  { id: 6861, name: "Youliao Studio" },
  { id: 7443, name: "YOYOmiracle" },
  { id: 6508, name: "Yudubai Animation" },
  { id: 96, name: "Yumeta Company" },
  { id: 6279, name: "Zero G Room" },
  { id: 6117, name: "Zero-G" },
  { id: 218, name: "ZEXCS" },
  { id: 6480, name: "Zhangyue Pictures" },
  { id: 6474, name: "Zhongce Picture" },
  { id: 7469, name: "Zhuo Hua Network" },
  { id: 7704, name: "Ziine Studio" },
  { id: 6549, name: "Zoland Animation" },
] as const;
const current = new Date().getFullYear();
const start = current + 2;
const end = 1941;
const years = [];
for (let y = start; y >= end; y--) {
  years.push(y);
}
export const yearEnums = years.map(String);
